### ISSUE TITLE
Zotero Citations: Scan reformats markdown

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#20]
Running Scan reformats my markdown. Is there a reason for this? Examples from a diff:

```
 - ***
 + * * *

 - * [Technologies](#technologies)
 + -   [??](#technologies)
   
 - ### Whole genome *de novo* assembly
 + ### Whole genome _de novo_ assembly

 - * **Genetic modification**.
 + -   **Genetic modification**.
```

It also looks like Scan trips over `[Technologies](#technologies)`, which is just meant as an internal page anchor, and not a reference. It would be better if Scan would leave cases like these alone, I think.

**Comment by retorquere** [comment]
The scanner uses a markdown parser and re-emitter (mdast) to do the work; I had a simple regex-based parser but too many edge cases existed. The triple-asterix case is weird, and I'll talk to the mdast author about that, but I have discussed changeless roundtripping with the mdast author before, and he didn't find that a very appealing project, deeming semantic equivalence sufficient.

As for the `[Technologies](#technologies)` issue, I don't know what to do about that. I suppose I could make the second form a selectable option, but it's exactly because it's an internal link that it works at all for the case described in the readme.

**Comment by rmzelle** [comment]
> As for the [Technologies](#technologies) issue, I don't know what to do about that.

It's converting "[Technologies]" to "[??]" because it can't match "(#technologies)" to a citation key, right? It would be nice if there was a setting to leave cases likes these (where no matching key exists) alone.

**Comment by rmzelle** [comment]
As for the other changes, it would be nice if the README at least warned the user about this.

**Comment by retorquere** [comment]
I've updated the README, and I've added an option to disable `#` link parsing. I don't want to leave cases like these because I can't distinguish between a citekey typo and an intentional internal anchor otherwise (or even an accidental match on a citekey for what was intended to be an internal anchor).

**Comment by rmzelle** [comment]
Thanks. Is there already a pref to use "Definition-style links" with the Pick command?

**Comment by rmzelle** [comment]
(bump)

> Is there already a pref to use "Definition-style links" ([(Heyns, 2014)][@heyns2014]) with the Pick command?

If there isn't, I'd like to put in a feature request for one. The "Definition-style links" aren't one of the options of "atom-zotero-citations", "pandoc", "mmd", "citet", or "citep", right?

**Comment by rmzelle** [comment]
And wouldn't it be better to convert `[Technologies](#technologies)` to something like `[?? Technologies ??](#technologies)` instead of `[??](#technologies)`. I'd prefer it if zotero-citations wouldn't delete any text.

**Comment by retorquere** [comment]
There isn't an option to choose between the two -- definition-style links don't work for multiple targets (the definition it would link to wouldn't exist), so currently atom-zotero-citations uses `@` (definition style) if you pick a single reference with no uppercase characters (because in MD, definition targets must be lowercase to be valid), and `#` otherwise. An option to choose would just mean you would be allowed to pick non-working variants.

WRT the second question, scan mode explicitly deletes text. If the reference to `#technologies` changes authors, the existing text would also be removed and replaced. You're right I could technically leave the text in place, but I don't yet have a visual on what it would achieve. The '??' is like latex which also replaces broken references thus. I could perhaps replace it with `??#technologies` (so question marks + the citation key(s)), but I don't understand where the capitalized version would come from.

**Comment by retorquere** [comment]
Or rather, if you replace `#technologies` with `#socialconstructionism`, the word Technologies wouldn't be very informative, certainly if it was the scanner that put Technologies there in the first place. I used to enter my references as `[](@tech)` and let the scanner take care of the label. I have fallen back to using LaTeX, so I don't use the plugin myself anymore.

**Comment by rmzelle** [comment]
> definition-style links don't work for multiple targets

What are "multiple targets"? You mean when you cite two items or more in a single citation? (e.g. "(Doe 2002; Smith 1950)"?)

> I could perhaps replace it with ??#technologies (so question marks + the citation key(s)), but I don't understand where the capitalized version would come from.

My example `[Technologies](#technologies)` is for an internal page anchor (there is a header named "Technologies"). When dealing with these markers that could either indicate an internal anchor or a zotero-citations marker, it seems better to not replace the link label "Technologies" with "??". `[??Technologies??](#technologies)` is lossless and much easier to revert to `[Technologies](#technologies)` than `[??](#technologies)`.

**Comment by rmzelle** [comment]
(I was hoping to use this plugin to add formatted reference to my markdown files (ideally via the picker), while still having the ability to use internal anchors. I'm still a bit unclear whether this is possible with the current version of the plugin because I'm a bit confused about the limitations of the definition-style markers)

**Comment by retorquere** [comment]
> What are "multiple targets"? You mean when you cite two items or more in a single citation? (e.g. "(Doe 2002; Smith 1950)"?)

Right, yes, with multiple targets I meant "when more than one item exists in a single citation, I can't construct a valid target for it"

> My example `[Technologies](#technologies)` is for an internal page anchor

Ah, right. Hrm, no, you wouldn't want them to be replaced, no.

> I was hoping to use this plugin to add formatted reference to my markdown files (ideally via the picker), while still having the ability to use internal anchors. I'm still a bit unclear whether this is possible with the current version of the plugin because I'm a bit confused about the limitations of the definition-style markers

Should be possible, if you  turn off scanning for anchor links.

**Comment by rmzelle** [comment]
> Should be possible, if you turn off scanning for anchor links.

Will you put out a new release?

**Comment by retorquere** [comment]
Sorry, thought I had done that already. .15 is out.
