### ISSUE TITLE
keymap suggestion

### ISSUE THREAD

**Issue by oztalha** [retorquere/zotero-citations#25]
I believe there has to be a default **keymap for pick** and that of course to be noted in the ReadMe. Since Atom [currently](https://github.com/atom/command-palette/issues/46) does not preserve the last command in the `command palette`, `pick`ing takes time without keymapping. For example, this keymap  `"shift-ctrl-Z": "zotero-citations:pick"` works for me (Z for Zotero), which I propose it to be a default setting.

**Comment by retorquere** [comment]
I think Atom has started discouraging extension-provided keymaps because too many conflicts occurred. I agree it's a little awkward, but to the best of my knowledge, [this](http://www.linux-magazine.com/Online/Blogs/Productivity-Sauce/Custom-Keybindings-in-the-Atom-Editor) is how you keep your own kepymappings persistent.
