### ISSUE TITLE
Definition-style links aren't corrected converted to HTML

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#28]
Converting the following scanned result to HTML with pandoc results in `<a href="@brown_genome_2013">(Brown et al., 2013)</a>`

Shouldn't this be `<a href="#brown_genome_2013">(Brown et al., 2013)</a>` (with a hash)?

```
This published genome [\(Brown et al., 2013\)](@brown_genome_2013)

[#bibliography]: #start

[@brown_genome_2013]: #brown_genome_2013 "Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. (2013). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_(3), e00323-13. http://doi.org/10.1128/genomeA.00323-13"

<a name="brown_genome_2013"></a>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. <http://doi.org/10.1128/genomeA.00323\-13>

[#bibliography]: #end
```

**Comment by retorquere** [comment]
There's several things going on here:

1. `[\(Brown et al., 2013\)](@brown_genome_2013)` should have been `[\(Brown et al., 2013\)][@brown_genome_2013]`, as it's the second syntax that triggers definition-style links. I've made changes to BBT to push those out correctly, but the link syntax would still be problematic. I don't currently have a good solution for this.
2. Pandoc treats `[\(Brown et al., 2013\)][@brown_genome_2013]` as `[\(Brown et al., 2013\)]` followed by the citation `[@brown_genome_2013]` rather than a reference link to `@brown_genome_2013`. I suppose that behavior won't change, so I'll have to use a different marker for def-style links than `@`

**Comment by rmzelle** [comment]
> but the link syntax would still be problematic

Why?

> I'll have to use a different marker for def-style links than @

Maybe [\(Brown et al., 2013\)][#brown_genome_2013]? That seems to work.

**Comment by retorquere** [comment]
It's problematic because I don't have a way to generate multi-cites; I
can't safely use a definition link, because what I can put in a definition
link is limited, which is why I started introducing anchor style links. But
anchor style links interfere with legitimate internal anchors. Maybe the
whole idea to use links wasn't all that great. Perhaps images would have
been better to abuse. I'll need to think about this to get to a sensible
spec. Or scholarly markdown would have to get to a spec. I don't know, but
the quick hack I made seems to have been ill conceived.

The hash does work, but I need to figure out a way to get the whole
citation thing right.

**Comment by rmzelle** [comment]
I'd be more than fine with a solution that doesn't use links, by the way. The main attraction of zotero-citations for me is to be able to quickly cite items from my Zotero library and get formatted citations. Even with non-linked cites that's already much better than copy-and-pasting formatted references.

**Comment by retorquere** [comment]
Except I forgot that abusing images this way would leave a broken image in
the resulting html. Bah. Markdown really only leaves links to abuse, but:

* definition style links really only work for single citations where the
key is all-lowercase alphanumeric
* faux-anchor links would sort of work, in the sense that they would render
correctly in-text, but for multi-cite, the link would always be broken, as
the bibliography can't generate the correct targets (in the bibliography,
there's no concept of bundles of citations), and people have legitimately
complained about the hijacking of anchor links.

The second could perhaps be ameliorated by using an unusual anchor prefix
like "#*", but if the citation links are going to be broken routinely
anyway, I could just as well pick "?keys". It wouldn't go anywhere, but at
least it wouldn't be a broken link.

**Comment by rmzelle** [comment]
Could you use HTML instead? https://daringfireball.net/projects/markdown/syntax#html: "For any markup that is not covered by Markdown’s syntax, you simply use HTML itself."

**Comment by retorquere** [comment]
It is in principle possible, but it's a nightmare to do. I can't speak on Markdown parsers in general, but the one I use (mdast) hands me these events when I parse e.g. `<cite key="latour_ny_2008">\(Latour, 2005/2008\)</cite><cite key="latour_ny_2009"><cite key="latour_ny_2010">`

1. html:`<cite key="latour_ny_2008">`
2. text:`(Latour, 2005/2008)`
3. html:`</cite>`
4. html:`<cite key="latour_ny_2009">`
5. html:`<cite key="latour_ny_2010">`

In other words, Markdown tolerates HTML more than that it supports it; I'd have to do enclosure tracking to see that 1. and 3. go together and enclose 2., and would have to implement a tag soup parser to prevent 4. from gobbling up all content that follows. I know 4. ought to have been `<cite key="latour_ny_2009"/>`, but people make mistakes, and given that this plugin actively changes the document, I'd rather not have the reaction to that mistake be "I guess you don't need any of the text that follows, let me replace that with a citation for you".

That seems like no fun at all. I'll give remark (another markdown-to-AST-to-markdown processor) a try, but the behavior above seems to be a feature of markdown, not a bug. Abusing known markdown tags takes care of such problems for me. But I'm also starting to see why Scholarly Markdown never really got off the ground.

**Comment by rmzelle** [comment]
> which is why I started introducing anchor style links. But
> anchor style links interfere with legitimate internal anchors.

I think I would be all set if zotero-citations had an option to just skip unrecognized anchors, so that I can still use internal anchors to point to in-document headers.

Looking at the citation support in https://atom.io/packages/markdown-preview-plus, though, maybe the easiest solution for me would just be to avoid the Scan feature, and insert "pandoc" style citation markers instead. I post-process my markdown files with pandoc anyway. I can then just point pandoc to use a .bib file that I export from Zotero and which I keep up-to-date with the BBT plugin.

**Comment by retorquere** [comment]
I can't distinguish between unrecognized anchors (which I should leave untouched) and mistyped citation keys (which I should process to alert you). I can't really think of a good option that is just commonmark, and yeah, pandoc is always going to beat that.

**Comment by rmzelle** [comment]
> I can't distinguish between unrecognized anchors (which I should leave untouched) and mistyped citation keys (which I should process to alert you).

Do you know if mdast makes it easy to determine what internal anchors already exist in a (processed) document? If zotero-citations just skips those, that would work too.

E.g. if I write:

```
# header 1
```

it would be nice zotero-citations would leave `[see above](#header-1)` alone.

**Comment by retorquere** [comment]
It could be easier than that. I could just abandon both definition-style links and the existing internal-anchor links to just use `[\(Brown et al., 2013\)](#*brown_genome_2013)`. The internal links were problematic from the get-go (I later found out) because there are limitations on what they keys may be, and I can't mix-and-match internal-anchor style and definition style (I have recently found out flowing out from this) because I can't pass that information to the citation processor; the bibliography itself can only be one style because of that. Given that definition-style links don't always work, I can only use internal-anchor links, with what is hopefully an uncommon prefix....

although come to think of it, I might as well use something like `[\(Brown et al., 2013\)](?brown_genome_2013)`. The link won't go anywhere useful, but at least it won't be broken, and it won't conflict with internal anchors. Even internal anchors like `[\(Brown et al., 2013\)](#*brown_genome_2013)` would have broken references for any multi-citations.

**Comment by retorquere** [comment]
I've removed the option and enabled two kinds of links: `[\(Brown et al., 2013\)](?@brown_genome_2013)` and `[\(Brown et al., 2013\)](#@brown_genome_2013)`. The corresponding change in BBT is running through the tests now.
