### ISSUE TITLE
PSA: picker works, scanner disabled

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-citations#40]
I must move the addin away from making sync requests (atom no longer allows them). I have updated the picker, but the scanner requires substantially more work. This is for the next release.

**Comment by duncdrum** [comment]
@retorquere any progress on this, or recommended workarounds?

**Comment by retorquere** [comment]
Not yet, no.

**Comment by michaelaye** [comment]
does this mean/could this effect the automatic export from zotero? I'm trying to set this all up, but currently my Keep-updated collection bibtex is not being updated after a zotero-picker action.

**Comment by retorquere** [comment]
No, this shouldn't affect the automatic export, and what you're experiencing must be a separate issue. Can you open a new issue under better-bibtex?

**Comment by CBenghi** [comment]
Hello @retorquere, 

until the problem is fixed I'd suggest that you put a warning in the readme for the package so that potential users will know that this is not working as expected at the moment, or if there's a workaround to produce the reference list list manually from other tools some guidance for that.

As a potential workaround would it be possible to generate both the in-text citation and the content for the reference list when picking from zotero? At that point we could manually move it to the reference section.

Thanks,
Claudio

**Comment by retorquere** [comment]
It's possible, yes, but will not happen short-term. I first need to attend to the rewrite of BBT for Zotero 5.0.

I've updated the README.
